sudo: required
services: 
    - docker
script:
    - docker build -t blemine/ci_testing .
    - docker images blemine/ci_just_a_test
before_deploy:
    - docker login -u sherlocklemine -p Apzoei102938
deploy:
    provider: script
    script: docker push blemine/ci_just_a_test
    on: 
        branch: master