sudo: required
services: 
    - docker
script:
    - docker build -t sherlocklemine/ci_testing .
    - docker images sherlocklemine/ci_testing
before_deploy:
    - docker login -u sherlocklemine -p Apzoei102938
deploy:
    provider: script
    script: docker push sherlocklemine/ci_testing
    on: 
        branch: master