sudo: required
services: 
    - docker
script:
    - docker build -t <username>/ci_testing .
    - docker images <username>/ci_testing
before_deploy:
    - docker login -u <username> -p <password>
deploy:
    provider: script
    script: docker push <username>/ci_testing
    on: 
        branch: master